"""
Sibyl Theme Engine
==================
Core of the entire theming system.

Flow:
  1. Page loads → boot_session hook calls inject_theme()
  2. inject_theme() resolves which theme applies to THIS user/company
  3. CSS is generated from the theme DocType fields
  4. CSS is cached in Redis (cleared on theme save)
  5. CSS is injected into frappe.boot → available as frappe.boot.sibyl_theme
  6. sibyl-core.js picks it up and injects <style> into <head> immediately

Per-client resolution order (most specific wins):
  User's Company → Sibyl Client → Active Theme → CSS
  Fallback: Global default theme → CSS
"""

import frappe
from frappe.model.document import Document


# ─────────────────────────────────────────────
#  DocType Controller
# ─────────────────────────────────────────────

class SibylTheme(Document):

    def on_update(self):
        self.clear_cache()
        if self.is_default and self.scope == "Global":
            self._unset_other_global_defaults()

    def on_trash(self):
        self.clear_cache()

    def clear_cache(self):
        """Clear all cached CSS for this theme."""
        frappe.cache.delete_key(f"sibyl:css:{self.name}")
        frappe.cache.delete_key("sibyl:css:global_default")
        # Clear per-client caches that use this theme
        frappe.cache.delete_keys("sibyl:css:client:*")

    def _unset_other_global_defaults(self):
        frappe.db.sql("""
            UPDATE `tabSibyl Theme`
            SET is_default = 0
            WHERE name != %s
              AND is_default = 1
              AND scope = 'Global'
        """, (self.name,))

    def to_css(self):
        """
        Generate the complete CSS string for this theme.
        This is the single source of truth for all styling.
        """
        t = self
        sp = int(t.spacing_unit or 4)
        r  = int(t.border_radius or 8)

        shadow_map = {
            "None":   "none",
            "Subtle": "0 1px 3px rgba(14,19,41,0.06), 0 2px 8px rgba(14,19,41,0.04)",
            "Medium": "0 4px 16px rgba(14,19,41,0.10)",
            "Strong": "0 8px 32px rgba(14,19,41,0.18)",
        }
        btn_radius_map = {
            "Rounded": f"{r}px",
            "Sharp":   "3px",
            "Pill":    "9999px",
        }
        font_stacks = {
            "Inter":             "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
            "DM Sans":           "'DM Sans', sans-serif",
            "Plus Jakarta Sans": "'Plus Jakarta Sans', sans-serif",
            "Geist":             "'Geist', sans-serif",
            "Manrope":           "'Manrope', sans-serif",
            "Rubik":             "'Rubik', sans-serif",
            "Nunito":            "'Nunito', sans-serif",
            "Poppins":           "'Poppins', sans-serif",
            "General Sans":      "'General Sans', sans-serif",
        }

        font   = font_stacks.get(t.font_family, font_stacks["Inter"])
        shadow = shadow_map.get(t.card_shadow, shadow_map["Subtle"])
        btn_r  = btn_radius_map.get(t.button_style, f"{r}px")

        # Input style
        input_styles = {
            "Default":    f"border: 1px solid var(--sibyl-border); border-radius: {r}px; background: var(--sibyl-card-bg);",
            "Filled":     f"border: 1px solid transparent; border-radius: {r}px; background: var(--sibyl-desk-bg);",
            "Underline":  "border: none; border-bottom: 2px solid var(--sibyl-border); border-radius: 0; background: transparent;",
        }
        input_css = input_styles.get(t.input_style, input_styles["Default"])

        css = f"""
/* ════════════════════════════════════════════════
   SIBYL ERP — Theme: {t.theme_name}
   Scope: {t.scope}
   Generated by Sibyl Theme Engine
═══════════════════════════════════════════════ */

:root {{

    /* ── Brand Colors ────────────────────────── */
    --sibyl-primary:        {t.primary_color or '#5B6AF0'};
    --sibyl-primary-dark:   {t.primary_dark or '#4755D4'};
    --sibyl-primary-light:  {t.primary_light or '#EEF0FD'};
    --sibyl-accent:         {t.accent_color or '#00C9A7'};
    --sibyl-success:        {t.success_color or '#2ECC71'};
    --sibyl-danger:         {t.danger_color or '#F0564A'};
    --sibyl-warning:        {t.warning_color or '#F5A623'};
    --sibyl-info:           {t.info_color or '#3498DB'};

    /* ── Surfaces ────────────────────────────── */
    --sibyl-navbar-bg:      {t.navbar_bg or '#0E1329'};
    --sibyl-sidebar-bg:     {t.sidebar_bg or '#0E1329'};
    --sibyl-desk-bg:        {t.desk_bg or '#F8F9FC'};
    --sibyl-card-bg:        {t.card_bg or '#FFFFFF'};
    --sibyl-text:           {t.text_primary or '#1C2240'};
    --sibyl-text-muted:     {t.text_muted or '#6E7A96'};
    --sibyl-border:         {t.border_color or '#E4E7F0'};

    /* ── Typography ──────────────────────────── */
    --sibyl-font:           {font};
    --sibyl-font-size:      {t.font_size_base or 13}px;
    --sibyl-line-height:    {t.line_height or 1.5};

    /* ── Spacing ─────────────────────────────── */
    --sibyl-sp-1:  {sp * 1}px;
    --sibyl-sp-2:  {sp * 2}px;
    --sibyl-sp-3:  {sp * 3}px;
    --sibyl-sp-4:  {sp * 4}px;
    --sibyl-sp-5:  {sp * 5}px;
    --sibyl-sp-6:  {sp * 6}px;
    --sibyl-sp-8:  {sp * 8}px;
    --sibyl-sp-10: {sp * 10}px;
    --sibyl-sp-12: {sp * 12}px;

    /* ── Radii ───────────────────────────────── */
    --sibyl-r-xs:  {max(r - 6, 1)}px;
    --sibyl-r-sm:  {max(r - 4, 2)}px;
    --sibyl-r-md:  {r}px;
    --sibyl-r-lg:  {r + 4}px;
    --sibyl-r-xl:  {r + 8}px;
    --sibyl-r-full: 9999px;

    /* ── Shadows ─────────────────────────────── */
    --sibyl-shadow-card: {shadow};
    --sibyl-shadow-sm:   0 2px 6px rgba(14,19,41,0.07);
    --sibyl-shadow-md:   0 4px 16px rgba(14,19,41,0.10);
    --sibyl-shadow-lg:   0 8px 32px rgba(14,19,41,0.14);
    --sibyl-shadow-xl:   0 16px 48px rgba(14,19,41,0.18);

    /* ── Layout ──────────────────────────────── */
    --sibyl-sidebar-w:  {t.sidebar_width or 220}px;
    --sibyl-navbar-h:   {t.navbar_height or 48}px;
    --sibyl-btn-r:      {btn_r};

    /* ── Transitions ─────────────────────────── */
    --sibyl-t-fast: {'120ms ease' if t.enable_animations else '0ms'};
    --sibyl-t-base: {'200ms ease' if t.enable_animations else '0ms'};
    --sibyl-t-slow: {'350ms cubic-bezier(0.4,0,0.2,1)' if t.enable_animations else '0ms'};

    /* ── Frappe Variable Bridge ──────────────── */
    --primary:               var(--sibyl-primary);
    --primary-color:         var(--sibyl-primary);
    --btn-primary-bg:        var(--sibyl-primary);
    --btn-primary-hover-bg:  var(--sibyl-primary-dark);
    --text-color:            var(--sibyl-text);
    --text-muted:            var(--sibyl-text-muted);
    --border-color:          var(--sibyl-border);
    --bg-color:              var(--sibyl-card-bg);
    --bg-light-gray:         var(--sibyl-desk-bg);
    --card-bg:               var(--sibyl-card-bg);
    --navbar-bg:             var(--sibyl-navbar-bg);
    --sidebar-bg:            var(--sibyl-sidebar-bg);
    --input-focus-border:    var(--sibyl-primary);
    --input-focus-shadow:    0 0 0 3px color-mix(in srgb, var(--sibyl-primary) 18%, transparent);
}}

/* ── Global Font ─────────────────────────────── */
body, .frappe-app {{
    font-family: var(--sibyl-font) !important;
    font-size: var(--sibyl-font-size) !important;
    line-height: var(--sibyl-line-height) !important;
    color: var(--sibyl-text) !important;
}}

/* ── Navbar ──────────────────────────────────── */
{_navbar_css(t)}

/* ── Sidebar ─────────────────────────────────── */
{_sidebar_css(t)}

/* ── Layout Dimensions ───────────────────────── */
.layout-side-section, .desk-sidebar {{
    width: var(--sibyl-sidebar-w) !important;
}}
.navbar {{ height: var(--sibyl-navbar-h) !important; min-height: var(--sibyl-navbar-h) !important; }}

/* ── Buttons ─────────────────────────────────── */
.btn {{
    font-family: var(--sibyl-font) !important;
    border-radius: var(--sibyl-btn-r) !important;
    transition: all var(--sibyl-t-base) !important;
}}
.btn-primary {{
    background: var(--sibyl-primary) !important;
    border-color: var(--sibyl-primary) !important;
    color: #fff !important;
}}
.btn-primary:hover {{
    background: var(--sibyl-primary-dark) !important;
    border-color: var(--sibyl-primary-dark) !important;
    transform: translateY(-1px);
    box-shadow: 0 4px 14px color-mix(in srgb, var(--sibyl-primary) 40%, transparent) !important;
}}

/* ── Inputs ──────────────────────────────────── */
.form-control, input[type="text"], input[type="email"],
input[type="password"], input[type="number"], textarea, select {{
    font-family: var(--sibyl-font) !important;
    {input_css}
    transition: border-color var(--sibyl-t-fast), box-shadow var(--sibyl-t-fast) !important;
}}

/* ── Cards ───────────────────────────────────── */
.frappe-card, .card, .widget {{
    background: var(--sibyl-card-bg) !important;
    border-radius: var(--sibyl-r-lg) !important;
    box-shadow: var(--sibyl-shadow-card) !important;
    border: 1px solid var(--sibyl-border) !important;
}}

/* ── Animations ──────────────────────────────── */
{'@keyframes sibyl-in { from { opacity:0; transform:translateY(5px); } to { opacity:1; transform:translateY(0); } }' if t.enable_animations else '* { animation: none !important; transition: none !important; }'}
"""

        # Dark mode block
        if t.enable_dark_mode:
            css += f"""
/* ── Dark Mode ───────────────────────────────── */
[data-theme="dark"], .dark-theme {{
    --sibyl-primary:    {t.dark_primary or '#7B8BF5'};
    --sibyl-navbar-bg:  {t.dark_navbar_bg or '#0B0E18'};
    --sibyl-sidebar-bg: {t.dark_sidebar_bg or '#0B0E18'};
    --sibyl-desk-bg:    {t.dark_desk_bg or '#0F1117'};
    --sibyl-card-bg:    #161B27;
    --sibyl-text:       #E4E8F5;
    --sibyl-text-muted: #5A6380;
    --sibyl-border:     rgba(255,255,255,0.07);
    --bg-color:         #161B27;
    --bg-light-gray:    {t.dark_desk_bg or '#0F1117'};
}}
"""

        # Per-module colors
        if t.module_colors:
            css += "\n/* ── Module Colors ───────────────────────── */\n"
            for row in t.module_colors:
                if row.hidden:
                    # Hide the entire module from sidebar
                    css += f"""
.standard-sidebar-item[data-module="{row.module_name}"],
.sidebar-item-container[data-module="{row.module_name}"] {{
    display: none !important;
}}
"""
                else:
                    mod_slug = row.module_name.lower().replace(" ", "-")
                    css += f"""
[data-module="{row.module_name}"] .sidebar-item-icon,
[data-module="{row.module_name}"] .standard-sidebar-item .icon {{
    color: {row.color} !important;
}}
[data-module="{row.module_name}"].standard-sidebar-item.selected {{
    background: color-mix(in srgb, {row.color} 15%, transparent) !important;
    color: {row.color} !important;
}}
"""

        # Custom CSS — always last, always wins
        if t.custom_css:
            css += f"\n/* ── Custom CSS ──────────────────────────── */\n{t.custom_css}\n"

        return css


# ─────────────────────────────────────────────
#  CSS component generators
# ─────────────────────────────────────────────

def _navbar_css(t):
    style = t.navbar_style or "Dark"
    base = f"""
.navbar, .navbar.navbar-default {{
    background: var(--sibyl-navbar-bg) !important;
    border-bottom: 1px solid rgba(255,255,255,0.05) !important;
    box-shadow: none !important;
}}
"""
    if style == "Light":
        return f"""
.navbar {{ background: #FFFFFF !important; border-bottom: 1px solid var(--sibyl-border) !important; }}
.navbar-nav > li > a {{ color: var(--sibyl-text-muted) !important; }}
.navbar-nav > li > a:hover {{ color: var(--sibyl-primary) !important; }}
.navbar-right > li > a {{ color: var(--sibyl-text-muted) !important; }}
.sibyl-brand-text {{ color: var(--sibyl-text) !important; }}
"""
    elif style == "Primary":
        return f"""
.navbar {{ background: var(--sibyl-primary) !important; border-bottom: 1px solid var(--sibyl-primary-dark) !important; }}
.navbar-nav > li > a {{ color: rgba(255,255,255,0.8) !important; }}
.navbar-nav > li > a:hover {{ color: #fff !important; }}
.sibyl-brand-text {{ color: #fff !important; }}
"""
    elif style == "Glass":
        return """
.navbar {
    background: rgba(14,19,41,0.65) !important;
    backdrop-filter: blur(20px) saturate(180%) !important;
    -webkit-backdrop-filter: blur(20px) saturate(180%) !important;
    border-bottom: 1px solid rgba(255,255,255,0.08) !important;
}
"""
    return base  # Dark default


def _sidebar_css(t):
    style = t.sidebar_style or "Dark"
    if style == "Light":
        return """
.layout-side-section, .desk-sidebar {
    background: #FFFFFF !important;
    border-right: 1px solid var(--sibyl-border) !important;
}
.standard-sidebar-item { color: var(--sibyl-text) !important; }
.standard-sidebar-item:hover { background: var(--sibyl-primary-light) !important; color: var(--sibyl-primary) !important; }
.standard-sidebar-item.selected { background: var(--sibyl-primary) !important; color: #fff !important; }
.sidebar-section-header { color: var(--sibyl-text-muted) !important; }
"""
    elif style == "Colored":
        return """
.layout-side-section, .desk-sidebar {
    background: var(--sibyl-primary) !important;
}
.standard-sidebar-item { color: rgba(255,255,255,0.72) !important; }
.standard-sidebar-item:hover { background: rgba(255,255,255,0.14) !important; color: #fff !important; }
.standard-sidebar-item.selected { background: rgba(255,255,255,0.22) !important; color: #fff !important; }
.sidebar-section-header { color: rgba(255,255,255,0.4) !important; }
"""
    elif style == "Glass":
        return """
.layout-side-section, .desk-sidebar {
    background: rgba(14,19,41,0.65) !important;
    backdrop-filter: blur(20px) saturate(180%) !important;
    -webkit-backdrop-filter: blur(20px) saturate(180%) !important;
    border-right: 1px solid rgba(255,255,255,0.06) !important;
}
"""
    # Dark (default)
    return """
.layout-side-section, .desk-sidebar {
    background: var(--sibyl-sidebar-bg) !important;
    border-right: 1px solid rgba(255,255,255,0.05) !important;
}
.standard-sidebar-item { color: rgba(255,255,255,0.58) !important; }
.standard-sidebar-item:hover { background: rgba(255,255,255,0.07) !important; color: rgba(255,255,255,0.9) !important; }
.standard-sidebar-item.selected { background: var(--sibyl-primary) !important; color: #fff !important; }
.sidebar-section-header { color: rgba(255,255,255,0.28) !important; font-size:10px; text-transform:uppercase; letter-spacing:0.08em; }
"""


# ─────────────────────────────────────────────
#  Theme Resolution Engine
# ─────────────────────────────────────────────

def resolve_theme_for_user(user=None):
    """
    Resolves which theme applies to the current user.
    Resolution order (most specific wins):
      1. User's company → Sibyl Client → active_theme
      2. Global default theme (is_default=1, scope='Global')
      3. None (no theme)
    """
    if not user:
        user = frappe.session.user

    # Step 1: Try to find user's company → client → theme
    try:
        user_company = frappe.db.get_value("User", user, "company") \
                    or frappe.db.get_single_value("Global Defaults", "default_company")

        if user_company:
            client = frappe.db.get_value(
                "Sibyl Client",
                {"company": user_company, "status": ["in", ["Active", "Trial"]]},
                ["name", "active_theme"],
                as_dict=True
            )
            if client and client.active_theme:
                return client.active_theme, "client"
    except Exception:
        pass

    # Step 2: Global default
    global_default = frappe.db.get_value(
        "Sibyl Theme",
        {"is_default": 1, "is_active": 1, "scope": "Global"},
        "name"
    )
    if global_default:
        return global_default, "global"

    # Step 3: Any active theme
    any_theme = frappe.db.get_value(
        "Sibyl Theme",
        {"is_active": 1},
        "name",
        order_by="creation asc"
    )
    return any_theme, "fallback"


def get_theme_css(theme_name, bust_cache=False):
    """Get CSS for a theme, using Redis cache."""
    cache_key = f"sibyl:css:{theme_name}"

    if not bust_cache:
        cached = frappe.cache.get_value(cache_key)
        if cached:
            return cached

    try:
        theme = frappe.get_doc("Sibyl Theme", theme_name)
        css = theme.to_css()
        frappe.cache.set_value(cache_key, css, expires_in_sec=7200)
        return css
    except Exception:
        frappe.log_error("Sibyl: Could not generate theme CSS", frappe.get_traceback())
        return ""


# ─────────────────────────────────────────────
#  Boot Hook — inject into every page
# ─────────────────────────────────────────────

def inject_theme_on_boot(bootinfo):
    """
    Called via boot_session hook in hooks.py.
    Injects theme data into frappe.boot so sibyl-core.js
    can apply it immediately — zero flash of unstyled content.
    """
    try:
        theme_name, source = resolve_theme_for_user()
        if not theme_name:
            return

        css = get_theme_css(theme_name)
        theme_doc = frappe.get_cached_doc("Sibyl Theme", theme_name)

        bootinfo.sibyl_theme = frappe._dict({
            "name":            theme_name,
            "source":          source,
            "css":             css,
            "app_name":        theme_doc.app_name_override or "Sibyl ERP",
            "logo":            theme_doc.logo or "",
            "favicon":         theme_doc.favicon or "",
            "show_brand_text": theme_doc.show_brand_text,
            "enable_dark_mode":theme_doc.enable_dark_mode,
            "primary_color":   theme_doc.primary_color or "#5B6AF0",
            "font_family":     theme_doc.font_family or "Inter",
            "module_config":   _get_module_config(theme_doc),
        })

    except Exception:
        frappe.log_error("Sibyl: Theme boot injection failed", frappe.get_traceback())


def _get_module_config(theme_doc):
    """Returns module visibility and color config for JS."""
    config = {}
    if theme_doc.module_colors:
        for row in theme_doc.module_colors:
            config[row.module_name] = {
                "color":  row.color,
                "icon":   row.icon or "",
                "hidden": bool(row.hidden),
            }
    return config


# ─────────────────────────────────────────────
#  Whitelisted API Endpoints
# ─────────────────────────────────────────────

@frappe.whitelist(allow_guest=True)
def get_active_theme_css():
    """Public endpoint — returns CSS for current user's theme."""
    theme_name, _ = resolve_theme_for_user()
    if not theme_name:
        return ""
    return get_theme_css(theme_name)


@frappe.whitelist()
def get_theme_preview_css(theme_name):
    """Returns CSS for a specific theme (for live preview in builder)."""
    frappe.has_permission("Sibyl Theme", throw=True)
    return get_theme_css(theme_name, bust_cache=True)


@frappe.whitelist()
def save_theme_from_builder(theme_data):
    """
    Called from the theme builder JS.
    Saves all theme values and returns fresh CSS.
    """
    frappe.only_for(["System Manager", "Sibyl Admin"])

    import json
    if isinstance(theme_data, str):
        theme_data = json.loads(theme_data)

    name = theme_data.get("theme_name")
    if not name:
        frappe.throw("Theme name is required")

    # Get or create
    if frappe.db.exists("Sibyl Theme", name):
        doc = frappe.get_doc("Sibyl Theme", name)
    else:
        doc = frappe.new_doc("Sibyl Theme")

    # Map builder fields → DocType fields
    field_map = {
        "theme_name":       "theme_name",
        "app_name":         "app_name_override",
        "primary_color":    "primary_color",
        "primary_dark":     "primary_dark",
        "primary_light":    "primary_light",
        "accent_color":     "accent_color",
        "success_color":    "success_color",
        "danger_color":     "danger_color",
        "warning_color":    "warning_color",
        "info_color":       "info_color",
        "navbar_bg":        "navbar_bg",
        "sidebar_bg":       "sidebar_bg",
        "desk_bg":          "desk_bg",
        "card_bg":          "card_bg",
        "text_primary":     "text_primary",
        "text_muted":       "text_muted",
        "border_color":     "border_color",
        "font_family":      "font_family",
        "font_size_base":   "font_size_base",
        "line_height":      "line_height",
        "border_radius":    "border_radius",
        "spacing_unit":     "spacing_unit",
        "sidebar_width":    "sidebar_width",
        "navbar_height":    "navbar_height",
        "card_shadow":      "card_shadow",
        "sidebar_style":    "sidebar_style",
        "navbar_style":     "navbar_style",
        "button_style":     "button_style",
        "input_style":      "input_style",
        "enable_animations":"enable_animations",
        "show_brand_text":  "show_brand_text",
        "enable_dark_mode": "enable_dark_mode",
        "dark_primary":     "dark_primary",
        "dark_navbar_bg":   "dark_navbar_bg",
        "dark_sidebar_bg":  "dark_sidebar_bg",
        "dark_desk_bg":     "dark_desk_bg",
        "custom_css":       "custom_css",
        "is_default":       "is_default",
        "scope":            "scope",
        "client":           "client",
    }

    for builder_key, doc_field in field_map.items():
        if builder_key in theme_data:
            setattr(doc, doc_field, theme_data[builder_key])

    # Module colors
    if "module_colors" in theme_data:
        doc.module_colors = []
        for mc in theme_data["module_colors"]:
            doc.append("module_colors", {
                "module_name": mc.get("name") or mc.get("module_name"),
                "color":       mc.get("color"),
                "icon":        mc.get("icon", ""),
                "hidden":      mc.get("hidden", 0),
            })

    doc.is_active = 1
    doc.save(ignore_permissions=False)
    frappe.db.commit()

    return {
        "success":    True,
        "theme_name": doc.name,
        "css":        get_theme_css(doc.name, bust_cache=True),
    }


@frappe.whitelist()
def set_client_theme(client_name, theme_name):
    """Assign a theme to a specific client."""
    frappe.only_for(["System Manager", "Sibyl Admin"])
    client = frappe.get_doc("Sibyl Client", client_name)
    client.active_theme = theme_name
    client.save()
    frappe.db.commit()

    # Bust client cache
    frappe.cache.delete_key(f"sibyl:css:client:{client_name}")

    return {"success": True}


@frappe.whitelist()
def get_all_themes():
    """Returns all active themes for the admin panel."""
    frappe.has_permission("Sibyl Theme", throw=True)
    themes = frappe.get_all(
        "Sibyl Theme",
        filters={"is_active": 1},
        fields=["name", "theme_name", "scope", "client", "is_default",
                "primary_color", "navbar_style", "sidebar_style", "font_family"],
        order_by="is_default desc, creation asc"
    )
    return themes


@frappe.whitelist()
def get_all_clients():
    """Returns all clients for admin panel."""
    frappe.only_for(["System Manager", "Sibyl Admin"])
    return frappe.get_all(
        "Sibyl Client",
        fields=["name", "client_name", "status", "plan", "active_theme",
                "max_users", "site_name", "contact_email"],
        order_by="status, client_name"
    )
